import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { HomeService } from '../../../services/home.service';
import { environment } from '../../../../environments/environment';
import { timeStamp } from 'console';
import { airports } from '../../flight/airports';

@Component({
  selector: 'app-deal',
  templateUrl: './deal.component.html',
  styleUrls: ['./deal.component.scss']
})
export class DealComponent implements OnInit {

  s3BucketUrl = environment.s3BucketUrl;
  @Output() toString = new EventEmitter<string>();
  @Input()  dealList;
  list;
  constructor(
    private homeService : HomeService
  ) {}

  ngOnInit() {
    var airlines={
      '0B': "Blue Air Airline Management",
      '0V': "Vietnam Air Service Company",
      '8H': "Balkan Holidays",
      '1L': "West? Air? Express",
      '1X': "Branson Air",
      '2A': "Deutsche Bahn",
      '2B': "Albawings",
      '2C': "Sncf",
      '2D': "Eastern Airlines",
      '2E': "Smokey Bay Air",
      '2F': "Fair Aviation",
      '2H': "Thalys International",
      '2I': "Star Peru",
      '2J': "Air Burkina",
      '2K': "Avianca Ecuador",
      '2L': "Helvetic Airways",
      '2M': "Maya Island Air",
      '2N': "Nextjet",
      '2O': "Island Air",
      '2P': "Pal Express",
      '2R': "Via Rail",
      '2S': "Air Carnival",
      '2T': "Turbo Megha Air",
      '2U': "Sun D'or Airline",
      '2V': "Amtrak",
      '2W': "Welcome Air",
      '3A': "Chu Kong Trans",
      '3C': "Air Chathams",
      '3D': "Denim Air",
      '3E': "Air Choice",
      '3F': "Pacific Airways",
      '3H': "Air Inuit",
      '3J': "Jubba Airways Ltd",
      '3K': "Jetstar Asia Air",
      '3M': "Silver Airways",
      '3N': "Air Urga",
      '3O': "Air Arabia",
      '3P': "Air Philip",
      '3S': "Air Antilles",
      '3U': "Sichuan Airlines",
      '3V': "Asl Airlines Belgium",
      '3X': "Premier Trans Aire",
      '3Y': "Uniways",
      '3Z': "Travel Service Polska",
      '4A': "Aerodynamics",
      '4B': "Boutique Air",
      '4C': "Lan Colombia",
      '4D': "Air Sinai",
      '4E': "Tanana Air",
      '4F': "Air City",
      '4G': "Gazpromavia",
      '4H': "United Airways Bangladesh",
      '4I': "Ihy Izmir",
      '4J': "Flydamas Airline",
      '4K': "Kenn Borek Air",
      '4L': "Lineas Aereas Suramericanas",
      '4M': "Latam Argentina",
      '4N': "Air North",
      '4O': "Interjet",
      '4P': "Regional Sky",
      '4Q': "Safi Airways",
      '4R': "Renfe Viajeros",
      '4T': "Transwest Air",
      '4U': "Germanwings",
      '4W': "Warbelows Air",
      '4Y': "Airbus Transport International",
      '4Z': "South African Ai",
      '5B': "Bassaka Air",
      '5C': "Nature Air",
      '5D': "Aeromexico Cnct",
      '5E': "East Coast Flight Services, Inc",
      '5F': "Fly One",
      '5H': "Five Forty",
      '5J': "Cebu Pacific Air",
      '5K': "Hi Fly",
      '5M': "Montserrat Airways Ltd",
      '5N': "Nordavia Airline",
      '5O': "Asl Airlines",
      '5R': "Rutaca",
      '5S': "Profesionales",
      '5T': "Canadian North",
      '5U': "Tag Airlines",
      '5V': "Lviv Airlines",
      '5W': "Speed Alliance",
      '5Y': "Atlas Air",
      '5Z': "Cemair",
      '6B': "Tuifly Nordic Ab",
      '6C': "Air Timor S. A.",
      '6D': "Travel Service",
      '6E': "Indigo",
      '6G': "Executive Express Aviation Llc",
      '6H': "Israir",
      '6J': "Solaseed",
      '6K': "Kyrgyz Transavia",
      '6L': "Aklak Inc",
      '6O': "Orbest",
      'Y3': "Gryphon Airlines",
      '6Q': "Cham Wings",
      '6R': "Alrosa Air Co.",
      '6S': "Saudi Gulf Air",
      '6T': "Air Mandalay",
      '6V': "Avanza",
      '6W': "Saratov Airlines",
      '6Y': "Smartlynx Air",
      '7B': "Fly Bluecrane",
      '7C': "Jeju Air",
      '7E': "Sylt Air",
      '7F': "First Air",
      '7G': "Star Flyer",
      '7H': "Corvus Airlines",
      '7I': "Insel Air",
      '7J': "Tajik Air",
      '7K': "Kogalymavia",
      '7L': "Silk Way West",
      '7M': "Mayair, S.a. De C.v.",
      '7N': "Pawa Dominicana",
      '7P': "Air Panama",
      '7Q': "Elite Airways",
      '7R': "Rusline",
      '7T': "Aero Express",
      '7V': "Federal Airlines",
      '7W': "Wind Rose",
      '7Y': "Mann Airlines",
      '8A': "Atlas Blue",
      '8F': "Stp Airways",
      '8G': "Angel? Airlines",
      '8I': "Insel Air Aruba",
      '8J': "Ecojet",
      '8K': "K-mile Air",
      '8L': "Lucky Air",
      '8M': "Myanmar Airways",
      '8P': "Pacific Coastal",
      '8Q': "Onur Air",
      '8S': "Turbojet",
      '8T': "Air Tindi",
      '8U': "Afriqiyah",
      '8Y': "Air Burundi",
      '9A': "Eaglexpress Air Charter",
      '9B': "Accesrail",
      '9C': "Spring Airlines",
      '9D': "Toumai Air Tchad",
      '9E': "Endeavor Air",
      '9F': "Eurostar",
      '9G': "Airport Express Rail",
      '9H': "Changan Airlines",
      '9J': "Dana Airlines",
      '9K': "Cape Air",
      '9M': "Central Mtn Air",
      '9N': "Tropic Air",
      '9P': "Petra Airline",
      '9Q': "Caicos Express",
      '9R': "Satena",
      '9S': "Southern Air Inc.",
      '9T': "Travelspan",
      '9U': "Air Moldova",
      '9V': "Avior Airlines",
      '9W': "Jet Airways",
      '9X': "Southern Airways",
      'VB': "Aeroenlaces? Nacionales",
      'A0': "Aviancaargentina",
      'A2': "Astra Airlines",
      'A3': "Aegean Air",
      'A4': "Azimuth Airlines",
      'A5': "Hop",
      'A6': "Yunnan Hong Tu",
      'A7': "Calafia Airlines",
      'A8': "Benin Golf Air",
      'A9': "Georgian Airways",
      'AA': "American",
      'AB': "Air Berlin",
      'AC': "Air Canada",
      'AD': "Azul Linhas",
      'AE': "Mandarin Air",
      'AF': "Air France",
      'AG': "Aruba Airlines",
      'AH': "Air Algerie",
      'AI': "Air India",
      'AJ': "Aerocontractors",
      'AK': "Airasia",
      'AM': "Aeromexico",
      'AN': "Advanced Air",
      'AO': "Air Juan",
      'AP': "Airone S.p.a",
      'AQ': "Aloha Airlines",
      'AR': "Aerolineas Argen",
      'AS': "Alaska Airlines",
      'AT': "Royal Air Maroc",
      'AU': "Austral Lineas",
      'AV': "Avianca",
      'AW': "Africa World Air",
      'AX': "Trans States Air",
      'AY': "Finnair",
      'AZ': "Alitalia",
      'B0': "La Compagnie",
      'B2': "Belavia",
      'B3': "Bellview Airlines",
      'B4': "Zanair",
      'B5': "East African Saf",
      'B6': "Jetblue Airways",
      'B7': "Uni Airways",
      'B8': "Eritrean Air",
      'B9': "Iran Airtour Air",
      'BA': "British Airways",
      'BB': "Seaborne",
      'BC': "Skymark Airlines",
      'BD': "Bayon Airlines",
      'BE': "Flybe",
      'BF': "French Bee",
      'BG': "Biman Bangladesh",
      'BH': "Bismillah Airlines",
      'BI': "Royal Brunei",
      'BJ': "Nouvelair Tunisi",
      'BK': "Okay Airways",
      'BL': "Jetstar Pacific",
      'BM': "British Midland",
      'BO': "Bb Airways Pvt Ltd",
      'BP': "Air Botswana",
      'BQ': "Aeromar Air",
      'BR': "Eva Airways",
      'BS': "Us Bangla",
      'BT': "Air Baltic",
      'BU': "Caa",
      'BV': "Blu-express",
      'BW': "Caribbean Air",
      'BX': "Air Busan",
      'BY': "Thomson Airways",
      'BZ': "Blue Bird Airway",
      'C0': "One Caribbean",
      'C2': "Ceiba Intercon",
      'C3': "Trade Air Ltd",
      'C4': "Conquest Air Inc.",
      'C5': "Commutair",
      'C6': "Canjet",
      'C7': "Cinnamon Air",
      'C8': "Cronus Airlines",
      'C9': "Alphaland Inc",
      'CA': "Air China",
      'CB': "Scotairways",
      'CC': "Cm Airlines",
      'CD': "Alliance Air",
      'CE': "Chalair",
      'CF': "China Postal Airlines",
      'CG': "Png Air",
      'CI': "China Airlines",
      'CJ': "Ba City Flyer",
      'CL': "Lufthansa City",
      'CM': "Copa Airlines",
      'CN': "Grand China Air",
      'CO': "Cobalt Aero",
      'CP': "Compass Airlines",
      'CS': "Comlux Aruba Nv",
      'CT': "Alitalia City",
      'CU': "Cubana Airlines",
      'CV': "Cargolux",
      'CW': "Air Cargo Global",
      'CX': "Cathay Pacific",
      'CY': "Charlie Airlines",
      'CZ': "China Southern",
      'D1': "Direct Air & Tours",
      'D2': "Severstal",
      'D3': "Daallo Airlines",
      'D4': "Dart Ltd",
      'D5': "Dauair",
      'D6': "Inter Air",
      'D7': "Airasia X",
      'D8': "Norwegian",
      'D9': "Dena Airways",
      'DA': "Air Georgia",
      'DB': "Maleth-aero",
      'DC': "Braathens Regional Airways",
      'DD': "Nok Air",
      'DE': "Condor",
      'DF': "Condor Berlin",
      'DG': "Cebgo",
      'DH': "Independence Air",
      'DI': "Divi Divi Air",
      'DJ': "Air Asia Japan",
      'DK': "Thomas Cook Scandinavia",
      'DL': "Delta",
      'DM': "Anda Air Limited",
      'DN': "Norwegian Air",
      'DO': "Sky High",
      'DP': "Pobeda",
      'DQ': "Alexandria Air",
      'DR': "Ruili Airlines",
      'DS': "Easyjet Switzerland Sa",
      'DT': "Angola Airlines",
      'DV': "Air Company Scat",
      'DX': "Danish Air",
      'DY': "Norwegian Air",
      'E3': "Newgen Airways",
      'E4': "Enter Air Spolka Z.o.o.",
      'E5': "Air Arabia Egypt",
      'E6': "Bringer Air Cargo Taxi Aereo",
      'E8': "City Airways",
      'E9': "Evelop Airlines",
      'EA': "European Express",
      'EB': "Wamos Air",
      'EC': "Openskies",
      'ED': "Airexplore",
      'EF': "Strategic? Airlines",
      'EG': "Ernest Airline",
      'EH': "Ana Wings",
      'EI': "Aer Lingus",
      'EJ': "New England",
      'EK': "Emirates",
      'EL': "Ellinair S A",
      'EM': "Aero Benin",
      'EN': "Air Dolomiti",
      'EO': "Pegas Fly",
      'EP': "Iran Asseman",
      'EQ': "Tame Airlines",
      'ER': "Serene Air",
      'ET': "Ethiopian Air",
      'EU': "Chengdu Airlines",
      'EV': "Expressjet",
      'EW': "Eurowings",
      'EX': "Santo Domingo",
      'EY': "Etihad Airways",
      'EZ': "Sun Air Scandina",
      'F5': "Aerotranscargo",
      'F6': "Fly Compass",
      'F7': "Etihad Regional",
      'F8': "Flair Airlines",
      'F9': "Frontier",
      'FA': "Safair",
      'FB': "Bulgaria Air",
      'FC': "Fast Colombia S.a.s",
      'FD': "Dba Viva Colombia",
      'FF': "Tower Air",
      'FG': "Ariana Afghan Airlines",
      'FH': "Freebird Airline",
      'FI': "Icelandair",
      'FJ': "Fiji Airways",
      'FK': "Keewatin Air",
      'FL': "Airtran Airways",
      'FM': "Shanghai",
      'FN': "Fastjet Plc",
      'FO': "Flybondi",
      'FP': "Pelican Airlines",
      'FQ': "Sol Lineas",
      'FR': "Ryanair",
      'FS': "Flyglobal Charter Sdn. Bhd.",
      'FT': "Flyegypt",
      'FU': "Fuzhou Airlines",
      'FV': "Rossiya Airlines",
      'FW': "Ibex Airlines",
      'FY': "Firefly",
      'FZ': "Flydubai",
      'G3': "Gol",
      'G4': "Allegiant Air",
      'G5': "China Express",
      'G6': "Aura Airlines",
      'G7': "Gojet Airlines",
      'G8': "Go Air",
      'G9': "Air Arabia",
      'GA': "Garuda",
      'GC': "Global Feeder Services",
      'GD': "Grandstar Cargo International Airlines",
      'GE': "Transasia Airway",
      'GF': "Gulf Air",
      'GH': "Globus Llc",
      'GJ': "Zhejiang Loong",
      'GK': "Jetstar Japan",
      'GL': "Air Greenland",
      'GM': "Germania",
      'GP': "Apg Airlines",
      'GQ': "Sky Express",
      'GR': "Aurigny Air Svc",
      'GS': "Tianjin Airlines",
      'GT': "Air Guilin",
      'GU': "Aviateca",
      'GV': "Grant Aviation",
      'GX': "Guangxi Beibu",
      'GY': "Colorful Guizhou",
      'GZ': "Air Rarotonga",
      'H1': "Hahn Air Systems",
      'H2': "Sky Airline",
      'H3': "Air Berlin Aviation Gmbh",
      'H4': "Aero4m D.o.o",
      'H5': "Thomas Cook Airlines Balearics",
      'H6': "Hageland",
      'H7': "Taron-avia",
      'H8': "Auric Air Services",
      'HA': "Hawaiian",
      'HC': "Air Senegal",
      'HD': "Airdo",
      'HE': "Lgw",
      'HF': "Air Ivory Coast",
      'HG': "Niki",
      'HH': "Taban Airlines",
      'HI': "Papillon",
      'HK': "Skippers Aviatio",
      'HM': "Air Seychelles",
      'HO': "Juneyao Airlines",
      'HQ': "Thomas Cook Airlines Belgium N.v",
      'HR': "Hahn Air Lines",
      'HS': "Heli Securite",
      'HT': "Tianjin Air Cargo Co., Ltd",
      'HU': "Hainan Airlines",
      'HV': "Transavia",
      'HW': "North-wright",
      'HX': "Hong Kong Air",
      'HY': "Uzbekistan",
      'HZ': "Jsc Aurora",
      'I2': "Iberia Express",
      'I4': "Scott Air Llc",
      'I5': "Airasia",
      'I7': "Inter Iles Air",
      'I8': "Aboriginal Air",
      'I9': "Air Italy",
      'IA': "Iraqi Airways",
      'IB': "Iberia",
      'IC': "Indian Airlines",
      'ID': "Batik Air",
      'IE': "Solomon Airlines",
      'IF': "Fly Baghdad Airl",
      'IG': "Meridiana",
      'IH': "Southern Sky Jsc",
      'IJ': "Spring Airlines",
      'IK': "Air Kiribati",
      'IM': "Jsc Aircompany",
      'IN': "Nam Air",
      'IQ': "Qazaq Air",
      'IR': "Iran Air",
      'IS': "Sepehran Air",
      'IT': "Tigerair Taiwan",
      'IV': "Cardiff Aviation Malta",
      'IW': "Wings Air",
      'IX': "Air India Exp",
      'IY': "Yemenia Yemen",
      'IZ': "Arkia Israeli",
      'J0': "Jetlink Express",
      'J2': "Azerbaijan Airl",
      'J3': "Northwestern Air",
      'J5': "Alaska Seaplane",
      'J6': "Jamaica Air",
      'J7': "Afrijet",
      'J8': "Berjaya Air",
      'J9': "Jazeera Airways",
      'JA': "Jetsmart Spa",
      'JB': "Helijet Intl Inc",
      'JC': "Japan Air Commut",
      'JD': "Capital Airlines",
      'JE': "Mango",
      'JF': "Jet Asia Airways",
      'JH': "Fuji Dream",
      'JI': "San Juan Aviatio",
      'JJ': "Latam Brazil",
      'JK': "Spanair",
      'JL': "Japan Airlines",
      'JM': "Jambojet",
      'JN': "Joon",
      'JO': "Royal Wings",
      'JP': "Adria Airways",
      'JQ': "Jetstar Airways",
      'JR': "Joy Air",
      'JS': "Air Koryo",
      'JT': "Lion Air",
      'JU': "Air Serbia",
      'JV': "Bearskin Airline",
      'JW': "Vanilla Air",
      'JX': "Dac Aviation",
      'JY': "Intercaribbean",
      'JZ': "Jubba Airways",
      'K2': "Yute Commuter",
      'K3': "Taquan Air Svc",
      'K5': "Silverstone Air",
      'K6': "Cambodia Angkor",
      'K7': "Air Kbz Ltd",
      'K8': "Kan Air",
      'K9': "Esen Air",
      'KA': "Cathay Dragon",
      'KB': "Druk Air",
      'KC': "Air Astana",
      'KD': "Kalstar Aviation",
      'KE': "Korean Air Lines",
      'KF': "Air Belgium",
      'KG': "Key Lime Air Corporation",
      'KI': "Krasavia",
      'KK': "Atlasglobal",
      'KL': "KLM",
      'KM': "Air Malta",
      'KN': "China United",
      'KO': "Alaska Express",
      'KP': "Asky",
      'KQ': "Kenya Airways",
      'KR': "Cambodia Airways",
      'KS': "Penair",
      'KU': "Kuwait Airways",
      'KV': "Sky Regional",
      'KW': "Korea Express Airlines",
      'KX': "Cayman Airways",
      'KY': "Kunming Airlines",
      'L5': "Atlas Atlantique Airlines",
      'L6': "Mauritania",
      'L8': "Afric Aviation",
      'LA': "Latam Group",
      'LB': "Bul Air Ltd.",
      'LC': "Encompass Aviation, Llc",
      'LD': "Ahk Air Hong Kong",
      'LE': "Lugansk Airlines",
      'LF': "Corporate Flight",
      'LG': "Luxair",
      'LH': "Lufthansa",
      'LI': "Liat Ltd",
      'LJ': "Jin Air",
      'LK': "Lao Skyway",
      'LL': "Miami Air",
      'LM': "Loganair Limited",
      'LN': "Libyan Airlines",
      'LO': "Lot Polish",
      'LP': "Latam Peru",
      'LR': "Avianca Cr",
      'LS': "Jet2.com",
      'LT': "Longjiang",
      'LU': "Transporte Aereo",
      'LV': "Openskies",
      'LW': "Law - Latin American Wings",
      'LX': "Swiss",
      'LY': "El Al Israel",
      'LZ': "Swiss Global Air Lines Ag",
      'M0': "Aero Mongolia",
      'M3': "Latam Cargo Brasil",
      'M4': "Mistral Air",
      'M5': "Kenmore Air",
      'M6': "Amerijet International, Inc.",
      'M8': "Magnum. Air, Inc Dba Skyjet",
      'M9': "Motor Sich",
      'MA': "Malev Hungarian Airlines",
      'MC': "Air Mobility Command",
      'MD': "Air Madagascar",
      'ME': "Middle East",
      'MF': "Xiamen Airlines",
      'MH': "Malaysia Airline",
      'MI': "Silkair",
      'MJ': "Myway Airlines",
      'MK': "Air Mauritius",
      'ML': "Air Mediterranee",
      'MM': "Peach Aviation",
      'MN': "Comair",
      'MO': "Calm Air Intl",
      'MP': "Martinair",
      'MQ': "Envoy Air Inc",
      'MR': "Hunnu Air",
      'MS': "Egyptair",
      'MT': "Thomas Cook Air",
      'MU': "China Eastern",
      'MV': "Air Mediterranea",
      'MW': "Mokulele Airline",
      'MX': "Mexicana De Aviacion",
      'MY': "Maya Island Air",
      'MZ': "Amakusa Airlines",
      'N3': "Aerolineas Mas",
      'N4': "Nord Wind",
      'N5': "Nolinor Aviation",
      'N7': "Nordic Regional",
      'N8': "National Air",
      'N9': "Shree Airlines",
      'NA': "Nesma Airlines",
      'NB': "Skypower Express",
      'NC': "Northern Air Cargo, Inc.",
      'ND': "Fmi Air",
      'NE': "Sky Europe Airlines",
      'NF': "Air Vanuatu",
      'NG': "Al Naser",
      'NH': "All Nippon",
      'NI': "Portugalia Air",
      'NJ': "Niger Airways",
      'NK': "Spirit Airlines",
      'NL': "Shaheen Air International",
      'NM': "Manx2",
      'NN': "Vim Airlines",
      'NO': "Neos",
      'NP': "Nile Air",
      'NQ': "Air Japan",
      'NR': "Al-naser Airlines",
      'NS': "Hebei Airlines",
      'NT': "Binter Canarias",
      'NU': "Japan Trans Air",
      'NV': "Iranian Naft Airlines",
      'NW': "Northwest Airlines",
      'NX': "Air Macau",
      'NY': "Air Iceland Cnct",
      'NZ': "Air New Zealand",
      'O2': "Linear Air",
      'O4': "Antrak Air",
      'O5': "Comores Aviation",
      'O6': "Avianca Brazil",
      'O8': "Siam Air Transport Company Limited",
      'O9': "Nova Airways",
      'OA': "Olympic Air",
      'OB': "Boliviana",
      'OC': "Oriental Air",
      'OD': "Malindo Airways",
      'OE': "Laudamotion Gmbh",
      'OF': "Overland Airways",
      'OG': "Ghodawat Enterprises",
      'OH': "Psa Airlines",
      'OI': "Hinterland Aviation",
      'OJ': "Fly Jamaica Air",
      'OK': "Czech Airlines",
      'OL': "Samoa Airways",
      'OM': "Mongolian",
      'ON': "Nauru Airlines",
      'OO': "Skywest",
      'OP': "Dac Int Airlines",
      'OQ': "Chongqing Air",
      'OR': "Tui Fly",
      'OS': "Austrian Airline",
      'OT': "Aeropelican Air Services",
      'OU': "Croatia Airlines",
      'OV': "Estonian Air",
      'OX': "Orient Thai",
      'OY': "Andes Lineas",
      'OZ': "Asiana Airlines",
      'P0': "Proflight",
      'P2': "Airkenya Express",
      'P4': "Air Peace",
      'P5': "Aero Republica",
      'P6': "Pascan Aviation",
      'P7': "Small Planet Airlines",
      'P8': "Sprintair",
      'P9': "Peruvian Airline",
      'PA': "Airblue",
      'PB': "Pal Airlines",
      'PC': "Pegasus Airlines",
      'PD': "Porter Airlines",
      'PE': "Altenrhein",
      'PF': "Palestinian Airlines",
      'PG': "Bangkok Airways",
      'PH': "Phoenix Air Group, Inc",
      'PI': "Polar Airlines Ltd",
      'PJ': "Air Saint-pierre",
      'PK': "Pakistan Air",
      'PL': "Southern Air Cht",
      'PN': "China West Air",
      'PQ': "Airasia Philippines",
      'PR': "Philippine",
      'PS': "Ukraine Intl",
      'PU': "Plus Ultra Linea",
      'PV': "Saint Barth",
      'PW': "Precision Air",
      'PX': "Air Niugini",
      'PY': "Surinam Airways",
      'PZ': "Latam Paraguay",
      'Q2': "Maldivian",
      'Q3': "Anguilla Air Services",
      'Q4': "Starlink",
      'Q5': "Forty Mile Air",
      'Q6': "Volaris Costa Rica",
      'Q7': "Skybahamas",
      'Q8': "Trans? Air? Congo",
      'QA': "Cimber A/s",
      'QB': "Faraz Qeshm Airline",
      'QC': "Camair Co",
      'QD': "Jc (cambodia) International Airlines",
      'QE': "Express Freighte",
      'QF': "Qantas Airways",
      'QG': "Qualiflyer Group",
      'QH': "Air Kyrgyzstan",
      'QI': "Cimber Sterling",
      'QJ': "Latpass Airlines",
      'QK': "Air Canada Jazz",
      'QL': "Laser Airlines",
      'QM': "Monacair",
      'QN': "Skytrans Airline",
      'QQ': "Alliance Air Pty",
      'QR': "Qatar Airways",
      'QS': "Smartwings",
      'QU': "Utair Ukraine",
      'QV': "Lao Airlines",
      'QW': "Qingdao Airline",
      'QX': "Horizon Air",
      'QZ': "Indonesia Air",
      'R2': "Transair Senegal",
      'R3': "Yakutia",
      'R4': "Rus Aviation",
      'R5': "Jordan Aviation",
      'R6': "Dot Lt",
      'R7': "Aserca Air",
      'RA': "Nepal Airlines",
      'RB': "Syrian Arab Air",
      'RC': "Atlantic Airways",
      'RE': "Stobart Air",
      'RF': "Erofey",
      'RG': "Rotanajet Aviation",
      'RI': "Air Costa Rica",
      'RJ': "Royal Jordanian",
      'RK': "Skyview Airways Co Dba Skyview",
      'RL': "Royal Falcon",
      'RM': "Airco Armenia",
      'RO': "Tarom-romanian",
      'RP': "Base Airlines",
      'RQ': "Kam Air",
      'RS': "Air Seoul",
      'RT': "Uvt Aero",
      'RV': "Air Canada Rouge",
      'RW': "Royal Air",
      'RX': "Regent Airways",
      'RY': "Royal Wings",
      'RZ': "Dba Jiangxi Air",
      'S0': "Aero Lineas Sosa",
      'S2': "Jetkonnect",
      'S3': "Santa Barbara Airlines C.a.",
      'S4': "Sata Intl",
      'S5': "Shuttle America",
      'S6': "Sunrise Airways",
      'S7': "Siberia Air",
      'S8': "Sounds Air",
      'S9': "Starbow Airlines",
      'SA': "South African",
      'SB': "Air Calin",
      'SC': "Shandong",
      'SD': "Sudan Airways",
      'SE': "Xl Airways",
      'SF': "Tassili Air",
      'SG': "Spice Jet",
      'SH': "Sharp Airlines",
      'SI': "Blue Island",
      'SJ': "Sriwijaya Air",
      'SK': "Sas",
      'SL': "Thai Lion",
      'SM': "Air Cairo",
      'SN': "Brussels Airline",
      'SO': "Apex Airlines",
      'SP': "Sata Air Acores",
      'SQ': "Singapore Airl",
      'SS': "Corsair",
      'ST': "Germania",
      'SU': "Aeroflot",
      'SV': "Saudi Arabian",
      'SW': "Air Namibia",
      'SX': "Sky Work Airlines",
      'SY': "Sun Country",
      'SZ': "Somon Air",
      'T0': "Taca Peru",
      'T2': "Fly Art",
      'T3': "Eastern Airways",
      'T4': "Rhoades Aviation Inc.",
      'T5': "Turkmenistan",
      'T6': "1time",
      'T7': "Twin Jet",
      'T8': "Tran African Air",
      'TA': "Taca Intl",
      'TB': "Tui Fly Belgium",
      'TC': "Air Tanzania",
      'TD': "Atlantis Armenia",
      'TE': "Skytaxi",
      'TF': "Bra Sverige Ab",
      'TG': "Thai Intl",
      'TH': "British Citiexpr",
      'TI': "Tropic Ocean",
      'TJ': "Tradewind",
      'TK': "Turkish Airlines",
      'TL': "Airnorth",
      'TM': "Lam",
      'TN': "Air Tahiti Nui",
      'TO': "Transavia Fr",
      'TP': "Air Portugal",
      'TQ': "Tandem Aero",
      'TR': "Scoot",
      'TS': "Air Transat",
      'TT': "Tigerair Au",
      'TU': "Tunis Air",
      'TV': "Tibet Airlines",
      'TW': "T Way Air Co",
      'TX': "Air Caraibes",
      'TY': "Air Caledonie",
      'TZ': "Tsaradia",
      'U2': "Easyjet",
      'U3': "Sky Gates Airlin",
      'U4': "Buddha Air",
      'U5': "Karinou Airlines",
      'U6': "Ural Airlines",
      'U7': "Air Uganda",
      'U8': "Armavia",
      'U9': "Tatarstan",
      'UA': "United",
      'UB': "Myanmar Airways",
      'UC': "Latam Chile",
      'UD': "Owen Air",
      'UE': "Bizair",
      'UF': "Petroleum Air",
      'UG': "Tunisair Express",
      'UH': "Atlasjet",
      'UI': "Eurocypria Air",
      'UJ': "Almasria Airline",
      'UK': "Vistara",
      'UL': "Srilankan",
      'UM': "Air Zimbabwe",
      'UN': "Business Aviation Asia",
      'UO': "Hong Kong Expres",
      'UP': "Bahamasair",
      'UQ': "Urumqi Airlines",
      'US': "Us Airways",
      'UT': "Utair",
      'UU': "Air Austral",
      'UV': "Universal Airways, Inc.",
      'UX': "Air Europa",
      'UZ': "Buraq Air",
      'V0': "Conviasa",
      'V2': "Avialeasing Aviation Co",
      'V3': "Carpatair",
      'V4': "Vieques Air Link",
      'V5': "Aerovias",
      'V6': "Vi Airlink",
      'V7': "Air Senegal International",
      'VA': "Virgin Au",
      'VC': "Viaair",
      'VD': "Kun Peng Airlines",
      'VE': "Easyfly S. A.",
      'VF': "Flyviking",
      'VG': "Vlm Airlines",
      'VH': "Viva Air Colombia",
      'VJ': "Vietjet Aviation",
      'VK': "Level Anisec",
      'VL': "Med-view Airline",
      'VM': "Max Air",
      'VN': "Vietnam Air",
      'VP': "Flyme",
      'VQ': "Novo Air",
      'VR': "Tacv Cabo Verde",
      'VS': "Virgin Atlantic",
      'VT': "Air Tahiti",
      'VU': "Veca Airline",
      'VV': "Viva Air Peru",
      'VW': "Aeromar",
      'VX': "Virgin America",
      'VY': "Vueling Airlines",
      'VZ': "Vietjet Air",
      'W2': "Flexflight Aps",
      'W3': "Arik Air",
      'W4': "Lc Busre Sac",
      'W5': "Mahan Air",
      'W6': "Wizz Air Hu",
      'W7': "Wings Of Lebanon",
      'W9': "Wizz Air Uk",
      'WA': "Klm Cityhopper",
      'WB': "Rwandair Express",
      'WC': "Islena Airlines",
      'WD': "Modern Transtport Aereo De Caarga Sa",
      'WE': "Thai Smile",
      'WF': "Wideroes Flyvese",
      'WG': "Sunwing",
      'WH': "Westair Benin",
      'WJ': "Air Labrador",
      'WK': "Edelweiss Air",
      'WL': "World Atlantic Airlines",
      'WM': "Windward Island",
      'WN': "Southwest",
      'WO': "World? Airways",
      'WP': "Island Air",
      'WQ': "Swift Air L.l.c.",
      'WR': "Westjet Encore",
      'WS': "Westjet",
      'WT': "Wasaya Airways",
      'WU': "Jetways Airlines",
      'WV': "Westair Aviation",
      'WW': "Wow Air",
      'WX': "City Jet",
      'WY': "Oman Air",
      'WZ': "Red Wings",
      'X3': "Tuifly",
      'X8': "Icaro",
      'X9': "Avion Express",
      'XC': "K.d. Air",
      'XD': "Bus",
      'XE': "Express Jet",
      'XF': "Mongolian Airways Cargo",
      'XG': "Sunexpress De",
      'XH': "Other Travel",
      'XJ': "Thai Air Asia X",
      'XK': "Ccm",
      'XL': "Latam Ecuador",
      'XM': "Zimex Aviation",
      'XN': "Travel Express",
      'XP': "Tem Enterprises",
      'XQ': "Sunexpress",
      'XR': "Corendon Airline",
      'XT': "Indonesia Airasi",
      'XU': "African Express",
      'XV': "Bvi Airways",
      'XW': "Nokscoot Airline",
      'XY': "Flynas",
      'XZ': "South African Ex",
      'Y0': "Yellow Air Taxi",
      'Y2': "Air Century",
      'Y4': "Volaris",
      'Y6': "Ab Aviation",
      'Y7': "Jsc Airline Taim",
      'Y9': "Kish Air",
      'YB': "Borajet",
      'YC': "Yamal Airlines",
      'YE': "Yanair",
      'YG': "Yto Cargo Airlines Co. Ltd",
      'YH': "Sunspalsh Llc",
      'YI': "Air Sunshine",
      'YK': "Avia Traffic Company",
      'YL': "Libyan Wings",
      'YM': "Montenegro",
      'YN': "Air Creebec",
      'YO': "Heli Air Monaco",
      'YP': "Perimeter Aviation Ltd",
      'YQ': "Tar Aerolineas",
      'YR': "Scenic Airlines",
      'YS': "Hop Regional",
      'YT': "Yeti Airlines",
      'YU': "Euroatlantic Air",
      'YV': "Mesa Airlines",
      'YW': "Air Nostrum",
      'YX': "Republic Airline Inc",
      'YZ': "Yourways",
      'Z2': "Phl. Airasia Inc",
      'Z3': "Tanana Air",
      'Z4': "Zagrosjet",
      'Z5': "Global Africa Aviation",
      'Z6': "Dnieproavia Joint Stock Aviation Co",
      'Z7': "Amaszonas",
      'Z8': "Amaszonas",
      'Z9': "Jsc Bek Air",
      'ZA': "Skywings Asia",
      'ZB': "Monarch Airlines",
      'ZC': "Flyafrica Zimbab",
      'ZD': "Ewa Air",
      'ZE': "Eastar Jet",
      'ZF': "Azur Air",
      'ZH': "Shenzhen Airline",
      'ZI': "Aigle Azur",
      'ZK': "Great Lakes",
      'ZL': "Regional Express",
      'ZM': "Air Manas",
      'ZN': "Naysa",
      'ZP': "Paranair",
      'ZQ': "Azman Air",
      'ZS': "Sol Air",
      'ZU': "Sunair Aviation",
      'ZV': "V Air Corporation",
      'ZW': "Air Wisconsin",
      'ZX': "Air Alliance"
    };
    var kesys = [];
    for (let key in airlines) {
      kesys.push(key);
    }
    // var obj = [{"0A.png","0B.png","0D.png","2B.png","2C.png","2E.png","2I.png","2J.png","2K.png","2L.png","2M.png","2N.png","2O.png","2P.png","2Q.png","2U.png","2W.png","2Y.png","2Z.png","3B.png","3C.png","3E.png","3F.png","3H.png","3I.png","3K.png","3L.png","3M.png","3O.png","3P.png","3R.png","3S.png","3T.png","3U.png","3W.png","3Y.png","3Z.png","3�.png","4C.png","4D.png","4E.png","4G.png","4H.png","4J.png","4K.png","4L.png","4M.png","4N.png","4O.png","4Q.png","4R.png","4T.png","4U.png","4V.png","4W.png","4Y.png","5C.png","5G.png","5H.png","5J.png","5L.png","5M.png","5N.png","5O.png","5P.png","5Q.png","5R.png","5T.png","5U.png","5V.png","5W.png","5Y.png","5Z.png","5�.png","6A.png","6C.png","6E.png","6F.png","6G.png","6H.png","6I.png","6J.png","6K.png","6L.png","6N.png","6P.png","6Q.png","6R.png","6S.png","6T.png","6V.png","6W.png","6Y.png","6Z.png","7C.png","7D.png","7E.png","7F.png","7G.png","7H.png","7I.png","7J.png","7K.png","7L.png","7M.png","7N.png","7P.png","7R.png","7V.png","7W.png","7Z.png","8B.png","8D.png","8E.png","8F.png","8G.png","8J.png","8L.png","8M.png","8N.png","8O.png","8P.png","8Q.png","8R.png","8T.png","8U.png","8V.png","8W.png","9B.png","9C.png","9D.png","9E.png","9F.png","9G.png","9H.png","9J.png","9K.png","9L.png","9M.png","9O.png","9R.png","9U.png","9V.png","9W.png","9X.png","9Y.png","A0.png","A2.png","A3.png","A4.png","A5.png","A6.png","A7.png","A8.png","A9.png","AA.png","AB.png","AC.png","AD.png","AE.png","AF.png","AH.png","AI.png","AJ.png","AK.png","AM.png","amtrak-logo.jpg","AO.png","AP.png","AQ.png","AR.png","AS.png","AT.png","AU.png","AV.png","AW.png","AX.png","AY.png","AZ.png","B2.png","B3.png","B5.png","B6.png","B7.png","B8.png","B9.png","BA.png","BB.png","BC.png","BD.png","BE.png","BF.png","BG.png","BH.png","BI.png","BJ.png","BK.png","BL.png","BN.png","BP.png","BR.png","BS.png","BT.png","BU.png","BV.png","BW.png","BX.png","C3.png","C4.png","C5.png","C7.png","C8.png","C9.png","CA.png","CB.png","CC.png","CE.png","CF.png","CG.png","CH.png","CI.png","CJ.png","CL.png","CM.png","CN.png","CO.png","CQ.png","CT.png","CU.png","CW.png","CX.png","CY.png","CZ.png","D2.png","D3.png","D4.png","D6.png","D7.png","D8.png","D9.png","db_train_100px.svg","DB.png","DC.png","DD.png","DE.png","DG.png","DH.png","DI.png","DJ.png","DL.png","DN.png","DO.png","DR.png","DT.png","DU.png","DV.png","DX.png","DY.png","DZ.png","E0.png","E3.png","E4.png","E5.png","E8.png","EA.png","EC.png","EE.png","EF.png","EG.png","EI.png","EJ.png","EK.png","EL.png","EN.png","EO.png","EP.png","EQ.png","ET.png","EU.png","EW.png","EY.png","EZ.png","F2.png","F5.png","F7.png","F9.png","FB.png","FC.png","FD.png","FE.png","FG.png","FI.png","FJ.png","FL.png","FM.png","FN.png","FO.png","FP.png","FQ.png","FR.png","FS.png","FT.png","FV.png","FW.png","FY.png","FZ.png","G0.png","G3.png","G4.png","G8.png","G9.png","GA.png","GE.png","GF.png","GI.png","GJ.png","GL.png","GQ.png","GR.png","GS.png","GT.png","GU.png","GV.png","GW.png","GY.png","GZ.png","H1.png","H2.png","H3.png","H4.png","H7.png","H8.png","H9.png","HA.png","HB.png","HD.png","HE.png","HF.png","HG.png","HH.png","HI.png","HM.png","HO.png","HR.png","HS.png","HT.png","HU.png","HV.png","HW.png","HX.png","HY.png","HZ.png","I2.png","I3.png","I4.png","I5.png","I7.png","I8.png","I9.png","IA.png","IB.png","IC.png","idtgv.jpg","IE.png","IF.png","IG.png","IH.png","IK.png","IN.png","IP.png","IQ.png","IR.png","IS.png","IT.png","IV.png","IX.png","IY.png","IZ.png","J0.png","J2.png","J3.png","J4.png","J5.png","J6.png","J7.png","J8.png","J9.png","JA.png","JB.png","JD.png","JE.png","JH.png","JJ.png","JK.png","JL.png","JM.png","JN.png","JO.png","JP.png","JQ.png","JR.png","JS.png","JT.png","JU.png","JV.png","JX.png","JY.png","JZ.png","K2.png","K3.png","K5.png","K6.png","K7.png","K8.png","K9.png","KA.png","KB.png","KC.png","KD.png","KE.png","KF.png","KG.png","KH.png","KI.png","KJ.png","KK.png","KL.png","KM.png","KN.png","KO.png","KQ.png","KR.png","KS.png","KT.png","KU.png","KV.png","KW.png","KX.png","KY.png","L3.png","L5.png","L6.png","L9.png","LA.png","LF.png","LG.png","LH.png","LI.png","LJ.png","LM.png","LN.png","LO.png","LP.png","LR.png","LS.png","LT.png","LV.png","LW.png","LX.png","LY.png","LZ.png","M2.png","M3.png","M5.png","M6.png","M7.png","M9.png","MA.png","MD.png","ME.png","MF.png","MH.png","MI.png","MJ.png","MK.png","ML.png","MM.png","MN.png","MO.png","MP.png","MS.png","MU.png","MW.png","MX.png","MY.png","MZ.png","N2.png","N3.png","N4.png","N5.png","N6.png","N7.png","N9.png","NA.png","NC.png","ND.png","NF.png","NG.png","NH.png","NI.png","NK.png","NL.png","NM.png","NN.png","NQ.png","NR.png","NS.png","NT.png","ntv.png","NU.png","NW.png","NX.png","NY.png","NZ.png","O2.png","O4.png","O6.png","O7.png","OA.png","OB.png","OC.png","OD.png","OF.png","OG.png","OK.png","OL.png","OM.png","ON.png","OP.png","OR.png","OS.png","OT.png","OU.png","OV.png","OX.png","OY.png","OZ.png","P0.png","P2.png","P3.png","P4.png","P5.png","P6.png","P8.png","P9.png","PB.png","PC.png","PD.png","PE.png","PG.png","PJ.png","PK.png","PL.png","PM.png","PN.png","PR.png","PS.png","PU.png","PV.png","PW.png","PX.png","PY.png","PZ.png","Q2.png","Q3.png","Q4.png","Q5.png","Q6.png","Q7.png","Q8.png","QB.png","QC.png","QF.png","QG.png","QH.png","QI.png","QK.png","QL.png","QM.png","QP.png","QR.png","QS.png","QU.png","QV.png","QW.png","QX.png","QZ.png","R2.png","R3.png","R4.png","R6.png","R7.png","RA.png","raileurope.png","RB.png","RC.png","RE.png","renfe.png","RG.png","RH.png","RI.png","RJ.png","RK.png","RL.png","RO.png","RQ.png","RT.png","RU.png","RV.png","RX.png","RZ.png","S0.png","S2.png","S3.png","S4.png","S5.png","S6.png","S7.png","S9.png","SA.png","SB.png","SC.png","SD.png","SE.png","SF.png","SG.png","SH.png","SI.png","SJ.png","SK.png","SL.png","SM.png","SN.png","SO.png","SP.png","SQ.png","SS.png","SU.png","SV.png","SW.png","SX.png","SY.png","T3.png","T4.png","T5.png","T6.png","T7.png","TA.png","TC.png","TD.png","TE.png","TF.png","TG.png","thetrainLine.jpg","TJ.png","TK.png","TL.png","TM.png","TN.png","TO.png","TP.png","TQ.png","TR.png","train_bene.png","train_db.png","train_eurostar.jpg","trenitalia.png","TS.png","TT.png","TU.png","TV.png","TW.png","TX.png","TY.png","TZ.png","U2.png","U3.png","U4.png","U5.png","U6.png","U7.png","U9.png","UA.png","UK.png","UL.png","VN.png","VS.png","VY.png","WB.png","WE.png","WS.png","WY.png","XQ.png","ZL.png"}];
    
    var keys2 =  ['0A.png','0B.png','0D.png','2B.png','2C.png','2E.png','2I.png','2J.png','2K.png','2L.png','2M.png','2N.png','2O.png','2P.png','2Q.png','2U.png','2W.png','2Y.png','2Z.png','3B.png','3C.png','3E.png','3F.png','3H.png','3I.png','3K.png','3L.png','3M.png','3O.png','3P.png','3R.png','3S.png','3T.png','3U.png','3W.png','3Y.png','3Z.png','3�.png','4C.png','4D.png','4E.png','4G.png','4H.png','4J.png','4K.png','4L.png','4M.png','4N.png','4O.png','4Q.png','4R.png','4T.png','4U.png','4V.png','4W.png','4Y.png','5C.png','5G.png','5H.png','5J.png','5L.png','5M.png','5N.png','5O.png','5P.png','5Q.png','5R.png','5T.png','5U.png','5V.png','5W.png','5Y.png','5Z.png','5�.png','6A.png','6C.png','6E.png','6F.png','6G.png','6H.png','6I.png','6J.png','6K.png','6L.png','6N.png','6P.png','6Q.png','6R.png','6S.png','6T.png','6V.png','6W.png','6Y.png','6Z.png','7C.png','7D.png','7E.png','7F.png','7G.png','7H.png','7I.png','7J.png','7K.png','7L.png','7M.png','7N.png','7P.png','7R.png','7V.png','7W.png','7Z.png','8B.png','8D.png','8E.png','8F.png','8G.png','8J.png','8L.png','8M.png','8N.png','8O.png','8P.png','8Q.png','8R.png','8T.png','8U.png','8V.png','8W.png','9B.png','9C.png','9D.png','9E.png','9F.png','9G.png','9H.png','9J.png','9K.png','9L.png','9M.png','9O.png','9R.png','9U.png','9V.png','9W.png','9X.png','9Y.png','A0.png','A2.png','A3.png','A4.png','A5.png','A6.png','A7.png','A8.png','A9.png','AA.png','AB.png','AC.png','AD.png','AE.png','AF.png','AH.png','AI.png','AJ.png','AK.png','AM.png','amtrak-logo.jpg','AO.png','AP.png','AQ.png','AR.png','AS.png','AT.png','AU.png','AV.png','AW.png','AX.png','AY.png','AZ.png','B2.png','B3.png','B5.png','B6.png','B7.png','B8.png','B9.png','BA.png','BB.png','BC.png','BD.png','BE.png','BF.png','BG.png','BH.png','BI.png','BJ.png','BK.png','BL.png','BN.png','BP.png','BR.png','BS.png','BT.png','BU.png','BV.png','BW.png','BX.png','C3.png','C4.png','C5.png','C7.png','C8.png','C9.png','CA.png','CB.png','CC.png','CE.png','CF.png','CG.png','CH.png','CI.png','CJ.png','CL.png','CM.png','CN.png','CO.png','CQ.png','CT.png','CU.png','CW.png','CX.png','CY.png','CZ.png','D2.png','D3.png','D4.png','D6.png','D7.png','D8.png','D9.png','db_train_100px.svg','DB.png','DC.png','DD.png','DE.png','DG.png','DH.png','DI.png','DJ.png','DL.png','DN.png','DO.png','DR.png','DT.png','DU.png','DV.png','DX.png','DY.png','DZ.png','E0.png','E3.png','E4.png','E5.png','E8.png','EA.png','EC.png','EE.png','EF.png','EG.png','EI.png','EJ.png','EK.png','EL.png','EN.png','EO.png','EP.png','EQ.png','ET.png','EU.png','EW.png','EY.png','EZ.png','F2.png','F5.png','F7.png','F9.png','FB.png','FC.png','FD.png','FE.png','FG.png','FI.png','FJ.png','FL.png','FM.png','FN.png','FO.png','FP.png','FQ.png','FR.png','FS.png','FT.png','FV.png','FW.png','FY.png','FZ.png','G0.png','G3.png','G4.png','G8.png','G9.png','GA.png','GE.png','GF.png','GI.png','GJ.png','GL.png','GQ.png','GR.png','GS.png','GT.png','GU.png','GV.png','GW.png','GY.png','GZ.png','H1.png','H2.png','H3.png','H4.png','H7.png','H8.png','H9.png','HA.png','HB.png','HD.png','HE.png','HF.png','HG.png','HH.png','HI.png','HM.png','HO.png','HR.png','HS.png','HT.png','HU.png','HV.png','HW.png','HX.png','HY.png','HZ.png','I2.png','I3.png','I4.png','I5.png','I7.png','I8.png','I9.png','IA.png','IB.png','IC.png','idtgv.jpg','IE.png','IF.png','IG.png','IH.png','IK.png','IN.png','IP.png','IQ.png','IR.png','IS.png','IT.png','IV.png','IX.png','IY.png','IZ.png','J0.png','J2.png','J3.png','J4.png','J5.png','J6.png','J7.png','J8.png','J9.png','JA.png','JB.png','JD.png','JE.png','JH.png','JJ.png','JK.png','JL.png','JM.png','JN.png','JO.png','JP.png','JQ.png','JR.png','JS.png','JT.png','JU.png','JV.png','JX.png','JY.png','JZ.png','K2.png','K3.png','K5.png','K6.png','K7.png','K8.png','K9.png','KA.png','KB.png','KC.png','KD.png','KE.png','KF.png','KG.png','KH.png','KI.png','KJ.png','KK.png','KL.png','KM.png','KN.png','KO.png','KQ.png','KR.png','KS.png','KT.png','KU.png','KV.png','KW.png','KX.png','KY.png','L3.png','L5.png','L6.png','L9.png','LA.png','LF.png','LG.png','LH.png','LI.png','LJ.png','LM.png','LN.png','LO.png','LP.png','LR.png','LS.png','LT.png','LV.png','LW.png','LX.png','LY.png','LZ.png','M2.png','M3.png','M5.png','M6.png','M7.png','M9.png','MA.png','MD.png','ME.png','MF.png','MH.png','MI.png','MJ.png','MK.png','ML.png','MM.png','MN.png','MO.png','MP.png','MS.png','MU.png','MW.png','MX.png','MY.png','MZ.png','N2.png','N3.png','N4.png','N5.png','N6.png','N7.png','N9.png','NA.png','NC.png','ND.png','NF.png','NG.png','NH.png','NI.png','NK.png','NL.png','NM.png','NN.png','NQ.png','NR.png','NS.png','NT.png','ntv.png','NU.png','NW.png','NX.png','NY.png','NZ.png','O2.png','O4.png','O6.png','O7.png','OA.png','OB.png','OC.png','OD.png','OF.png','OG.png','OK.png','OL.png','OM.png','ON.png','OP.png','OR.png','OS.png','OT.png','OU.png','OV.png','OX.png','OY.png','OZ.png','P0.png','P2.png','P3.png','P4.png','P5.png','P6.png','P8.png','P9.png','PB.png','PC.png','PD.png','PE.png','PG.png','PJ.png','PK.png','PL.png','PM.png','PN.png','PR.png','PS.png','PU.png','PV.png','PW.png','PX.png','PY.png','PZ.png','Q2.png','Q3.png','Q4.png','Q5.png','Q6.png','Q7.png','Q8.png','QB.png','QC.png','QF.png','QG.png','QH.png','QI.png','QK.png','QL.png','QM.png','QP.png','QR.png','QS.png','QU.png','QV.png','QW.png','QX.png','QZ.png','R2.png','R3.png','R4.png','R6.png','R7.png','RA.png','raileurope.png','RB.png','RC.png','RE.png','renfe.png','RG.png','RH.png','RI.png','RJ.png','RK.png','RL.png','RO.png','RQ.png','RT.png','RU.png','RV.png','RX.png','RZ.png','S0.png','S2.png','S3.png','S4.png','S5.png','S6.png','S7.png','S9.png','SA.png','SB.png','SC.png','SD.png','SE.png','SF.png','SG.png','SH.png','SI.png','SJ.png','SK.png','SL.png','SM.png','SN.png','SO.png','SP.png','SQ.png','SS.png','SU.png','SV.png','SW.png','SX.png','SY.png','T3.png','T4.png','T5.png','T6.png','T7.png','TA.png','TC.png','TD.png','TE.png','TF.png','TG.png','thetrainLine.jpg','TJ.png','TK.png','TL.png','TM.png','TN.png','TO.png','TP.png','TQ.png','TR.png','train_bene.png','train_db.png','train_eurostar.jpg','trenitalia.png','TS.png','TT.png','TU.png','TV.png','TW.png','TX.png','TY.png','TZ.png','U2.png','U3.png','U4.png','U5.png','U6.png','U7.png','U9.png','UA.png','UK.png','UL.png','VN.png','VS.png','VY.png','WB.png','WE.png','WS.png','WY.png','XQ.png','ZL.png'];
    
    console.log(JSON.stringify(keys2))
  }
  
  ngAfterContentChecked(){
    this.list = this.dealList;
  }

  btnDealClick(code : string){
    window.scrollTo({ left: 0, top: 0, behavior: 'smooth' });
    this.toString.emit(code);  
  }
}
